# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: # Contient la liste des filtres
        pack: # Nom du filtre
            quality: 85 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: { size: [ 200, 150 ], mode: outbound }


        carouselImages: # Nom du filtre
            quality: 85 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: { size: [ 2520, 1200 ]}