vich_uploader:
    db_driver: orm

    mappings:
        makeup_images:
            # alias for acced picture via navigator
            uri_prefix: /images/makeup
            # path stokage directory
            upload_destination: '%kernel.project_dir%/public/images/makeup'
            delete_on_update: true
            delete_on_remove: true


        theme_images:
            # alias for acced picture via navigator
            uri_prefix: /images/theme
            # path stokage directory
            upload_destination: '%kernel.project_dir%/public/images/theme'
            delete_on_update: true
            delete_on_remove: true


        packaging_images:
            # alias for acced picture via navigator
            uri_prefix: /images/packaging
            # path stokage directory
            upload_destination: '%kernel.project_dir%/public/images/packaging'
            delete_on_update: true
            delete_on_remove: true


        colours_images:
            # alias for acced picture via navigator
            uri_prefix: /images/colours
            # path stokage directory
            upload_destination: '%kernel.project_dir%/public/images/colours'
            delete_on_update: true
            delete_on_remove: true


        carousel_images:
            # alias for acced picture via navigator
            uri_prefix: /images/carousel
            # path stokage directory
            upload_destination: '%kernel.project_dir%/public/images/carousel'
            delete_on_update: true
            delete_on_remove: true
